FROM python:3.6.1-alpine

# Set the Current Working Directory inside the container
WORKDIR /api

# RUN  apt-get update
# RUN  apt-get install -y python3-dev python
# COPY ./requirements.txt .
# RUN pip install -r requirements.txt
EXPOSE 8080

CMD [“python”, “./app.py”] 